# Generated by Django 5.0.8 on 2024-08-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('culture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document', models.CharField(max_length=14)),
                ('producer_name', models.CharField(max_length=150)),
                ('farm_name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('total_area', models.FloatField()),
                ('arable_area', models.FloatField()),
                ('vegetation_area', models.FloatField()),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cultures', models.ManyToManyField(to='culture.culture')),
            ],
            options={
                'verbose_name': 'Produto Rural',
                'verbose_name_plural': 'Produtores Rurais',
                'ordering': ['id'],
            },
        ),
    ]
