# Generated by Django 5.0.8 on 2024-08-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0002_alter_culture_created_date_and_more'),
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='arable_area',
            field=models.FloatField(verbose_name='Área Agriculturável'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='cultures',
            field=models.ManyToManyField(to='culture.culture', verbose_name='Culturas'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='deleted_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deletado em'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='document',
            field=models.CharField(max_length=14, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='farm_name',
            field=models.CharField(max_length=150, verbose_name='Fazenda'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_name',
            field=models.CharField(max_length=150, verbose_name='Produtor'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='state',
            field=models.CharField(max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='total_area',
            field=models.FloatField(verbose_name='Área Total'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='vegetation_area',
            field=models.FloatField(verbose_name='Área de Vejetação'),
        ),
    ]
