# Generated by Django 5.0.8 on 2024-08-07 17:29

import producer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0002_alter_producer_arable_area_alter_producer_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producer',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='producer',
            old_name='updated_date',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='deleted_date',
        ),
        migrations.AlterField(
            model_name='producer',
            name='document',
            field=models.CharField(max_length=14, validators=[producer.validators.validate_document], verbose_name='CPF/CNPJ'),
        ),
    ]
