version: '3'

services:
  web:
    restart: always
    build: .
    command: gunicorn backend.wsgi:application -w 2 -b :8000
    links:
      - db:db
    volumes:
      - static:/usr/src/app/staticfiles
    expose:
      - 8000
    env_file: .env-docker
    depends_on:
      - db
    environment:
      DEBUG: 'true'
      DJANGO_SUPERUSER_PASSWORD: "admin"

  nginx:
    restart: always
    build: ./nginx
    volumes:
      - static:/usr/src/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web

  db:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=backend

volumes:
  pgdata:
  static: